# -*- coding: utf-8 -*-
"""TrainAndTestLLaMa.cpp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/115-2gsRujzLRIl9YewLoCv4ZUWH1YJuu
"""

!git clone https://github.com/cuongdl/llama.cpp.git

!ls -l

!ls -l llama.cpp

!pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd llama.cpp/

!ls -l
!pip install -r requirements.txt

!pip install --pre torch torchvision --extra-index-url https://download.pytorch.org/whl/nightly/cpu

!make

!mkdir build; cd build; cmake .. -DBUILD_TESTING=ON -DLLAMA_BUILD_EXAMPLES=ON; cmake --build .

!rm -f models/7B/*
!cd models/7B;wget https://huggingface.co/TheBloke/vicuna-7B-1.1-GGML/resolve/main/vicuna-7b-1.1.ggmlv3.q2_K.bin

!ls -l ./models/7B/
!./main -t 10 -ngl 32 -m ./models/7B/vicuna-7b-1.1.ggmlv3.q2_K.bin --color -c 2048 --temp 0.7 --repeat_penalty 1.1 -n -1 -p "### Instruction: Write a story about llamas\n### Response:"

!./main -m ./models/7B/vicuna-7b-1.1.ggmlv3.q2_K.bin \
        -t 8 \
        -n 128 \
        -p 'The first man on the moon was '

!cd build;cmake .. -DBUILD_TESTING=ON -DLLAMA_BUILD_EXAMPLES=ON; cmake --build .

!cd build; wget https://github.com/brunoklein99/deep-learning-notes/blob/master/shakespeare.txt

!cd build; ./bin/train-text-from-scratch \
        --vocab-model ../models/ggml-vocab.bin \
        --ctx 64 --embd 256 --head 8 --layer 16 \
        --checkpoint-in  chk-shakespeare-256x16.bin \
        --checkpoint-out chk-shakespeare-256x16.bin \
        --model-out ggml-shakespeare-256x16-f32.bin \
        --train-data "../LICENSE" \
        -t 4 -b 32 -n 32 --seed 1 --adam-iter 16 \
        --print-details-interval 0 --predict 16 --use-flash

!cd build; ./bin/quantize ggml-shakespeare-256x16-f32.bin ggml-shakespeare-256x16-f32_q4k.bin 15
!ls -l build

!./main -m ./build/ggml-shakespeare-256x16-f32_q4k.bin \
        -t 8 \
        -n 128 \
        -p 'The first man on the moon was'

from google.colab import files
files.download('./build/ggml-shakespeare-256x16-f32_q4k.bin')

!./main -m ./build/ggml-shakespeare-256x16-f32_q4k.bin --mirostat 2 --mirostat 2 --mirostat-lr 0.98 --mirostat-ent 5